# Numpy

### Numerical Python

Numpy is a fundamental package for scientific computing in python. it provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Numpy is widely used for numerical computation in various domains, including datascience, machine learning and engineering. 

Numpy handles, 1D(vector), 2D, 3D, and other high-dimensional array

In [2]:
# installation on Numpy
!pip install numpy

In [4]:
# importing numpy
import numpy as np

### Creating arrays
Creation of arrays involves using pythons numpy library, which provides a powerful array object called ndarray.

### Creating Arrays from Lists
Arrays can be created directly from python list using the numpy array function

In [9]:
# creating 1D(vector) array
arr1 = np.array([15, 30, 45, 60])
arr1

array([15, 30, 45, 60])

In [11]:
# convert list to array
i = [2, 4, 6, 8]
np.array(i)

array([2, 4, 6, 8])

In [17]:
# creating 2D array
arr2 = np.array([[2, 4, 6],[3, 5, 7],[1, 5, 10]])
arr2

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [ 1,  5, 10]])

### Array Attributes

In [35]:
# showing the array shape
arr1.shape

(4,)

In [23]:
arr2.shape

(3, 3)

In [33]:
#showing the array size
arr1.size

4

In [27]:
arr2.size

9

In [37]:
# showing the number of dimensions
arr1.ndim

1

In [31]:
arr2.ndim

2

### Creating Arrays using Built-in Functions

In [47]:
# Array filled with zeros as elements
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# Array filled with one as element
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
# identity matrix
# The diagonal is 1 and every other element are zeros
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Creating Arrays using Random Functions

In [60]:
# Creating arrays of float using random functions
# Numbers are generated randomly
# Can be used for arrays of different dimensions
np.random.random(5)

array([0.55607005, 0.31053623, 0.83373948, 0.43643494, 0.16704142])

In [62]:
# Getting randoms numbers but only for 1 dimesion
np.random.rand(5)

array([0.61760335, 0.56108081, 0.47835542, 0.36953746, 0.39760208])

In [64]:
np.random.random((3, 3))

array([[0.15847866, 0.97179998, 0.92107431],
       [0.21782588, 0.93949294, 0.01071811],
       [0.22558458, 0.51837668, 0.41837449]])

In [66]:
# Getting random numbers within a certain range
# randint is an integer
np.random.randint(1, 10, (3, 3))

array([[3, 2, 9],
       [9, 9, 8],
       [1, 7, 4]])

### Seed Reproducibility
it is used to replicate a random number. Hence, setting the same seed value ensures identical output

In [70]:
np.random.seed(25)
np.random.randint(1, 100, (4, 5))

array([[ 5, 63, 91, 16, 62],
       [24, 45, 51,  9, 29],
       [ 5, 90, 32, 70,  2],
       [40,  4, 89, 56,  4]])

### Basic Array Operations

In [73]:
arr1

array([15, 30, 45, 60])

In [155]:
# Adding value to the array - Broadcasting
# Converting to an array if you want to add to the value
arr1 + 10

array([25, 50, 55, 70])

In [79]:
arr3 = np.array([12, 24, 36, 48])

In [81]:
arr1 + arr3

array([ 27,  54,  81, 108])

In [83]:
# Multiplication of arrays
arr1 * arr3

array([ 180,  720, 1620, 2880])

In [87]:
arr4 = np.array([[2, 4, 6, 8], [1, 3, 5, 7], [3.4, 6.8, 9.4, 9.2]])
arr4

array([[2. , 4. , 6. , 8. ],
       [1. , 3. , 5. , 7. ],
       [3.4, 6.8, 9.4, 9.2]])

In [89]:
row = [2, 4, 6, 8]

In [91]:
arr4 + row

array([[ 4. ,  8. , 12. , 16. ],
       [ 3. ,  7. , 11. , 15. ],
       [ 5.4, 10.8, 15.4, 17.2]])

### Array Indexing and Slicing
Array indexing and slicing in numpy are powerful tools for manipulating subsets of data in arrays

In [96]:
# Indexing in array
arr1[3]

60

In [98]:
#Slicing in array
arr1[:3]

array([15, 30, 45])

In [102]:
arr4

array([[2. , 4. , 6. , 8. ],
       [1. , 3. , 5. , 7. ],
       [3.4, 6.8, 9.4, 9.2]])

In [108]:
# The first rows and all the column
arr4[0, :]

array([2., 4., 6., 8.])

In [110]:
# Getting the first and the second row and all the column
arr4[0:2, :]

array([[2., 4., 6., 8.],
       [1., 3., 5., 7.]])

### Modifying
This is changing of element in an array

In [113]:
arr1

array([15, 30, 45, 60])

In [117]:
arr1[1] = 40
arr1

array([15, 40, 45, 60])

### Array Manipulation
Array manipulation in NumPy refers to modifying arrays to fit desired shapes, sizes, or structures. This includes operations like reshaping, flattening, transposing, and concatenating arrays, among others. Here's a detailed explanation of reshaping, flattening, and transposing:

##### Reshaping
Reshaping involves changing the shape (dimensions) of an array without altering its data. The total number of elements must remain the same.

In [125]:
ary = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ary.size

10

In [127]:
# reshaping the array
reshaped_ary = ary.reshape(2, 5)
reshaped_ary

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Transposing
Transposing flips an array's axes. For example, rows become columns, and vice versa. This is especially useful for matrix operations and reshaping multi-dimensional data.

In [130]:
# Transposing the array
reshaped_ary.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

##### Flattening
Flattening reduces a multi-dimensional array to a 1D array. This operation is commonly used when you need to perform operations that require a single sequence of elements.

In [133]:
# flatten it back to it original shape
reshaped_ary.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Splitting
Array Splitting in NumPy refers to dividing an array into multiple subarrays. This is useful when you need to process or analyze parts of an array independently.

Splitting Methods in NumPy
- `np.split`: General-purpose splitting based on specified indices.
- `np.array_split`: Allows uneven splitting.
- `np.hsplit`: Splits along columns (horizontal split for 2D arrays).
- `np.vsplit`: Splits along rows (vertical split for 2D arrays).
- `np.dsplit`: Splits along the depth (third axis) for 3D arrays.

In [137]:
# Splitting the array
np.split(ary, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

##### Concatenating
In NumPy, concatenation refers to joining two or more arrays along a specified axis. The arrays must have compatible shapes along the axis being concatenated.

In [140]:
arry = np.array([2, 4, 6, 8])
arry

array([2, 4, 6, 8])

In [142]:
rays = np.array([3, 6, 8, 1])
rays

array([3, 6, 8, 1])

In [144]:
# Concatenating
np.concatenate((arry, rays))

array([2, 4, 6, 8, 3, 6, 8, 1])

### Mathematical Operations

In [147]:
x = np.array([2, 4, 6, 8])

In [149]:
# Finding the square root of an array
np.sqrt(x)

array([1.41421356, 2.        , 2.44948974, 2.82842712])

In [153]:
# Sum of the array
x.sum()

20